# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Deploy 
      uses: easingthemes/ssh-deploy@v2.0.7  
      env:   
          SSH_PRIVATE_KEY: ${{ secrets.TENGXUNYUN }}       
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"  
          REMOTE_HOST: "49.232.38.113"  
          REMOTE_USER: "root"   
          TARGET: "/File/僵尸企业画像/dist/"
